# Generated by Django 4.2.5 on 2023-09-29 01:44

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "thumbnail_sizes",
                    models.JSONField(
                        default=list,
                        help_text="A list of dict, each containing 'height' and 'width' for thumbnail sizes assumed to be in pixels",
                        validators=[plans.models.validate_thumbnail_sizes],
                    ),
                ),
                ("include_original_link", models.BooleanField(default=False)),
                ("generate_expiring_links", models.BooleanField(default=False)),
            ],
        ),
    ]
