# Generated by Django 4.2.5 on 2023-09-29 03:19

from django.db import migrations, models
import plans.models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_userplan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userplan",
            options={"verbose_name": "User Plan", "verbose_name_plural": "User Plans"},
        ),
        migrations.AlterField(
            model_name="plan",
            name="thumbnail_sizes",
            field=models.JSONField(
                default=list,
                help_text="A list of dict, each containing 'height' and 'width' in integers for thumbnail sizes assumed to be in pixels",
                validators=[plans.models.validate_thumbnail_sizes],
            ),
        ),
    ]
