# Generated by Django 4.2.5 on 2023-09-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0002_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="thumbnails",
            field=models.JSONField(
                blank=True, default=list, editable=False, help_text="List of thumbnails with height x width as key"
            ),
        ),
    ]
