# Generated by Django 4.2.5 on 2023-09-29 10:55

from django.db import migrations, models
import images.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0004_remove_image_thumbnails_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="expiry_in_seconds",
            field=models.PositiveIntegerField(blank=True, help_text="Optional expiry time in seconds", null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="thumbnail",
            field=models.ImageField(upload_to=images.models.upload_thumbnail),
        ),
    ]
